######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 23 18:58:27 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += button.cpp
