######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 27 10:09:31 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += button.cpp
