######################################################################
# Automatically generated by qmake (2.01a) Thu Oct 27 22:51:23 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += button.cpp
